common: &common
  adapter: mysql
  database: {{ pillar['rails-app']['name'] }}_production
  username: app
  password: {{ pillar['mysql']['server']['root_password'] }}
  host: localhost 
  port: 3306

production:
  <<: *common
staging:
  <<: *common
staging1:
  <<: *common
staging2:
  <<: *common
east:
  <<: *common
west:
  <<: *common
dev:
  <<: *common
live:
  <<: *common
