{% set reinforcement_node_ip = salt['mine.get']('reinforcement*.' + salt['grains.get']('circle') + '.*', 'network.ip_addrs').items()[0][1][0] %}

SERVER_TYPE: {{ salt['grains.get']('circle') }}
SERVER_HOSTNAME: {{ pillar['mysql']['server_hostname'] }}
SERVER_PORT: 443

FILE_STORAGE: s3

DEV_VARS_LOADED: false
RESET_PASSWORD: 123456

CLEAN_DB_FILE: db/Clean.sql
CLEAN_DB_NAME: trex_clean
CLEAN_DB_USER: test@test.us

AMAZON_ACCESS_KEY_ID: {{ pillar['app']['amazon_access_key_id'] }}
AMAZON_SECRET_ACCESS_KEY: {{ pillar['app']['amazon_secret_access_key'] }}
AMAZON_INDEXER_BUCKET: sfym-{{ salt['grains.get']('circle') }}-trexglobal

SOLR_HOST: {{ reinforcement_node_ip }}
SOLR_PORT: 8080

MONGO_HOST: {{ reinforcement_node_ip }}
MONGO_DATABASE: trex_index

# Check Printing
DNODE_HOST:  {{ pillar['app']['dnode_host'] }}
DNODE_PORT: false
DNODE_TOKEN: {{ pillar['app']['dnode_token'] }}

QUEUE_HOST: {{ reinforcement_node_ip }}
QUEUE_PORT: 22122

MAIL_HOST: {{ reinforcement_node_ip }}
MAIL_DOMAIN: simplifyem.com

AUTHORIZENET_LOGIN: {{ pillar['app']['authorizenet_login'] }}
AUTHORIZENET_PASS: {{ pillar['app']['authorizenet_pass'] }}
AUTHORIZENET_TEST: false

# Enable profiling
PROFILE_ENABLED: false

# Payment setup
ENABLE_ACHFEDERAL_REQUESTS: true
ENABLE_VOIDING_TRANSACTIONS: true
RISK_MANAGER_ENABLED: false
INTERNAL_PAYMENT_TESTING_MODE: false

# Set maintananace flag to temporary disable contact import provider
# insert list of disabled providers e.g. 'gmail, hotmail, aol, yahoo'
CONTACTS_IMPORT_MAINTAIN: ''

# Time travelling tool, will be overridden by Rails.root/TIME_TRAVEL_TO file
# TIME_TRAVEL_TO: false

# MT/MU Enable
ENABLE_MULTIUSER: true
